# Generated by Django 2.0.7 on 2018-08-01 06:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0002_auto_20180801_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 1, 6, 14, 12, 910261, tzinfo=utc)),
        ),
    ]
