# Generated by Django 2.0.7 on 2018-08-01 06:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0004_auto_20180801_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 1, 6, 19, 4, 861477, tzinfo=utc)),
        ),
    ]
