# Generated by Django 2.0.7 on 2018-07-31 13:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('campaign_id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('campaign_name', models.CharField(max_length=25)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('created_by', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime(2018, 7, 31, 13, 50, 33, 310582, tzinfo=utc))),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.datetime(2018, 7, 31, 13, 50, 33, 310606, tzinfo=utc))),
            ],
            options={
                'db_table': 'campaign',
            },
        ),
    ]
