# Generated by Django 2.0.7 on 2018-08-01 05:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('campaignmanagment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 1, 5, 58, 38, 315810, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 1, 5, 58, 38, 315942, tzinfo=utc)),
        ),
    ]
