# Generated by Django 2.0.5 on 2018-06-16 10:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('useremail', models.CharField(max_length=100)),
                ('userpassword', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2018, 6, 16, 16, 17, 45, 712122))),
                ('lastlogin', models.DateTimeField(default=datetime.datetime(2018, 6, 16, 16, 17, 45, 712150))),
            ],
        ),
    ]
