# Generated by Django 2.0.5 on 2018-06-15 05:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questions',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 6, 15, 11, 9, 11, 936974), verbose_name='date published'),
        ),
    ]
