# Generated by Django 2.0.5 on 2018-06-16 10:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20180615_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 6, 16, 16, 17, 45, 723566), verbose_name='date published'),
        ),
    ]
